"""Blog post generation — delegates to blog_generator, stores drafts."""

import hashlib
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

log = logging.getLogger("ingest.publisher")


async def generate_post(
    client: httpx.AsyncClient,
    blog_generator_url: str,
    topic: str,
    style: str = "technical",
    model: str = "deepseek-v4-flash",
    max_tokens: int = 2048,
    temperature: float = 0.7,
    timeout: float = 180.0,
) -> dict[str, Any]:
    """Generate a researched blog post via blog_generator."""
    resp = await client.post(
        f"{blog_generator_url}/generate-researched",
        json={
            "topic": topic,
            "style": style,
            "model": model,
            "max_tokens": max_tokens,
            "temperature": temperature,
        },
        timeout=timeout,
    )
    resp.raise_for_status()
    return resp.json()


def store_draft(
    output_dir: Path,
    title: str,
    category: str,
    tags: list[str],
    content: str,
    sources: list[dict],
    source_url: str,
    model: str,
    cost_usd: float,
    tokens: int,
) -> Path:
    """Store generated post as an MDX draft in the output directory."""
    output_dir.mkdir(parents=True, exist_ok=True)

    slug = hashlib.sha256(title.encode()).hexdigest()[:12]
    now = datetime.now(timezone.utc)

    # Build frontmatter
    tags_yaml = "\n  - ".join(tags)
    sources_yaml = "\n".join(f"  - {s.get('url', '')}: {s.get('title', '')}" for s in sources)

    mdx = f"""---
title: "{title}"
date: {now.strftime("%Y-%m-%d")}
category: "{category}"
tags: [{", ".join(repr(t) for t in tags)}]
excerpt: "Auto-generated from {source_url}"
generated: true
model: "{model}"
cost_usd: {cost_usd}
tokens: {tokens}
sources:
{sources_yaml}
---

{content}

---
*Generated by Substrate ingest pipeline · {model} · {tokens} tokens · \${cost_usd:.4f}*
"""

    path = output_dir / f"{slug}.mdx"
    path.write_text(mdx)
    log.info("draft_saved", title=title, path=str(path))
    return path
