# ======================================================================================
# DeepSearchStack - Definitive Docker Compose Configuration (Restored & Corrected)
# ======================================================================================

volumes:
  postgres_data:
  yacy_data:
  ollama_data:
    name: deepsearch_ollama_data
  redis_data:
  chimera_db:

networks:
  deepsearch_net:
    driver: bridge
    name: deepsearch_net

services:
  # --- CORE INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-searchdb}
      - POSTGRES_USER=${POSTGRES_USER:-searchuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-searchpass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: redis-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- AI SERVICES ---
  ollama-orchestrator:
    build:
      context: ../services/ollama-api-server-docker/src/api-gateway
      dockerfile: Dockerfile
    container_name: ollama-orchestrator-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ollama_data:/root/.ollama
    env_file: ../.env
    environment:
      - WORKER_IMAGE=${WORKER_IMAGE:-ollama/ollama:latest}
      - OLLAMA_DEFAULT_MODEL=${OLLAMA_DEFAULT_MODEL:-gemma:2b}
      - CHIMERA_NETWORK=deepsearch_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/instances"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  llm-gateway:
    build:
      context: ../services/llm_gateway
      dockerfile: Dockerfile
    container_name: llm-gateway-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    depends_on:
      ollama-orchestrator:
        condition: service_healthy
    env_file: ../.env
    environment:
      - OLLAMA_BASE_URL=http://ollama-orchestrator:8000/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

  # --- CORE LOGIC (DECOUPLED) ---
  search-gateway:
    build:
      context: ../services/search-gateway
      dockerfile: Dockerfile
    container_name: search-gateway-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    depends_on:
      redis:
        condition: service_healthy
    env_file: ../.env
    environment:
      - YACY_URL=http://yacy:8090
      - WHOOGLE_URL=http://whoogle:5000
      - SEARXNG_URL=http://searxng:8080

  search-agent:
    build:
      context: ../services/search-agent
      dockerfile: Dockerfile
    container_name: search-agent-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    depends_on:
      - llm-gateway
    env_file: ../.env
    environment:
      - LLM_GATEWAY_URL=http://llm-gateway:8080

  # --- USER INTERFACE & PROXY ---
  web-api:
    build:
      context: ../services/web-api
      dockerfile: Dockerfile
    container_name: web-api-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    depends_on:
      - search-agent
      - llm-gateway
      - search-gateway
    environment:
      - SEARCH_AGENT_URL=http://search-agent:8001
      - LLM_GATEWAY_URL=http://llm-gateway:8080
      - SEARCH_GATEWAY_URL=http://search-gateway:8002

  frontend:
    build:
      context: ../services/frontend
      dockerfile: Dockerfile
    container_name: frontend-1
    restart: unless-stopped
    networks:
      - deepsearch_net

  chimera-frontend:
    build:
      context: ../services/ollama-api-server-docker/src/chimera-frontend
      dockerfile: Dockerfile
    container_name: chimera-frontend-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    depends_on:
      - ollama-orchestrator
    env_file:
      - ../.env
    volumes:
      - chimera_db:/app/prisma

  reverse-proxy:
    build:
      context: ../services/reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    ports:
      - "${REVERSE_PROXY_BIND_IP:-127.0.0.1}:80:80"
    depends_on:
      - frontend
      - chimera-frontend
      - web-api

  # --- SEARCH BACKENDS ---
  yacy:
    image: yacy/yacy_search_server:latest
    container_name: yacy-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    volumes:
      - yacy_data:/opt/yacy_search_server/DATA
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/status.json"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 120s

  whoogle:
    image: benbusby/whoogle-search:latest
    container_name: whoogle-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    environment:
      - WHOOGLE_CONFIG_GET_ONLY=1

  searxng:
    image: searxng/searxng:latest
    container_name: searxng-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    volumes:
      - ../services/searxng/settings.yml:/etc/searxng/settings.yml
    cap_drop: [ALL]
    cap_add: [CHOWN, SETGID, SETUID, DAC_OVERRIDE]

  # --- UTILITY & DATA SERVICES ---
  vector-store:
    build:
      context: ../services/vector-store
      dockerfile: Dockerfile
    container_name: vector-store-1
    restart: unless-stopped
    networks:
      - deepsearch_net

  crawler:
    build:
      context: ../services/crawler
      dockerfile: Dockerfile
    container_name: crawler-1
    restart: unless-stopped
    networks:
      - deepsearch_net
    ports:
      - "8003:8000"
    environment:
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
