apiVersion: automation.deeps/v1
kind: Workflow
metadata:
  name: daily-morning-report
  description: "Daily morning report with weather, AI news, and geopolitical analysis"
spec:
  triggers:
    - type: "schedule"
      cron: "0 8 * * *"  # Daily at 8 AM
    - type: "api"
      endpoint: "/trigger/morning-report"
  tasks:
    - name: "weather-casablanca"
      type: "api"
      provider: "weather-service"
      parameters:
        method: "GET"
        url: "http://weather-service:8004/weather"
        query_params:
          country: "MA"
          city: "Casablanca"
      conditions: {}
      retries: 2
      timeout: 30
      
    - name: "ai-news-search"
      type: "search"
      provider: "agent"
      parameters:
        query: "latest breakthrough artificial intelligence research 2025"
        max_results: 10
        providers: ["whoogle", "searxng"]
      conditions: {}
      retries: 2
      timeout: 60
      
    - name: "geopolitical-news-search"
      type: "search"
      provider: "agent"
      parameters:
        query: "current geopolitical tensions international relations 2025"
        max_results: 10
        providers: ["whoogle", "searxng"]
      conditions: {}
      retries: 2
      timeout: 60
      
    - name: "summarize-ai-news"
      type: "llm"
      provider: "llm-gateway"
      dependsOn: ["ai-news-search"]
      parameters:
        provider: "gemini"
        messages:
          - role: "system"
            content: "You are a technology news analyst. Summarize the latest AI breakthroughs in a concise, engaging format. Focus on major developments, new research papers, and significant announcements. Use bullet points for clarity."
          - role: "user"
            content: "Summarize these latest AI developments: {{tasks.ai-news-search.result.answer}}"
        temperature: 0.4
      conditions: {}
      retries: 1
      timeout: 120
      
    - name: "summarize-geopolitical-news"
      type: "llm"
      provider: "llm-gateway"
      dependsOn: ["geopolitical-news-search"]
      parameters:
        provider: "gemini"
        messages:
          - role: "system"
            content: "You are a geopolitical analyst. Provide a concise summary of current international tensions and relations. Focus on major developments and their potential implications. Use bullet points for clarity."
          - role: "user"
            content: "Summarize these geopolitical developments: {{tasks.geopolitical-news-search.result.answer}}"
        temperature: 0.4
      conditions: {}
      retries: 1
      timeout: 120
      
    - name: "compile-morning-report"
      type: "llm"
      provider: "llm-gateway"
      dependsOn: ["weather-casablanca", "summarize-ai-news", "summarize-geopolitical-news"]
      parameters:
        provider: "gemini"
        messages:
          - role: "system"
            content: "You are a morning briefing editor. Compile a comprehensive, engaging daily report. Structure it with clear sections and maintain a professional yet approachable tone."
          - role: "user"
            content: |
              Create a daily morning report with these components:
              
              1. Weather in Casablanca, Morocco: {{tasks.weather-casablanca.result}}
              2. Bleeding-Edge AI News: {{tasks.summarize-ai-news.result}}
              3. Geopolitical Sentiments: {{tasks.summarize-geopolitical-news.result}}
              
              Format the report with clear headings, bullet points where appropriate, and make it engaging for a morning read.
        temperature: 0.3
      conditions: {}
      retries: 1
      timeout: 180
      
  outputs:
    - name: "daily-report"
      value: "{{tasks.compile-morning-report.result}}"
      destinations:
        - type: "file"
          path: "/data/reports/morning-report-{{workflow.timestamp}}.md"
        - type: "file"
          path: "/data/reports/latest-morning-report.md"